# Generated by Django 5.1.4 on 2025-01-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_register',
            fields=[
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('Pincode', models.CharField(max_length=20, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('address', models.TextField(null=True)),
                ('picture', models.ImageField(upload_to='static/userpic/')),
            ],
        ),
    ]
